[package]
authors = ["David Peter <mail@david-peter.de>"]
categories = ["command-line-utilities"]
description = "A command-line hex viewer"
homepage = "https://github.com/sharkdp/hexyl"
license = "MIT/Apache-2.0"
name = "hexyl"
readme = "README.md"
repository = "https://github.com/sharkdp/hexyl"
version = "0.9.0"
edition = "2018"

[dependencies]
ansi_term = "0.12"
anyhow = { version = "1.0.31", optional = true }
atty = { version = "0.2", optional = true }
libc = "0.2"
thiserror = { version = "1.0.19", optional = true }

[dependencies.clap]
version = "2"
default-features = false
features = ["suggestions", "color", "wrap_help"]
optional = true

[dev-dependencies]
assert_cmd = "1.0"
predicates = { version = "2.0", default-features = false }

[features]
default = ["cli"]
cli = ["anyhow", "atty", "clap", "thiserror"]

[profile.release]
lto = true
codegen-units = 1
